language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="mirage-block-unix"
   - TESTS=true
 matrix:
   - DISTRO=alpine OCAML_VERSION=4.04
   - DISTRO=alpine OCAML_VERSION=4.06
   - DISTRO=debian-stable OCAML_VERSION=4.04
   - DISTRO=debian-stable OCAML_VERSION=4.06
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.04
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.06
